name: Deploy Hugo site to Pages

on: push

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      TZ: America/Los_Angeles
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Fetch new posts from arXiv
        run: |
          python scripts/fetch.py --verbose

      - name: Commit and push new posts
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git pull origin HEAD:${{ github.ref }} || echo "No previous commits to pull"
          git add content/posts/*.md || echo "No new posts"
          git add fetched_papers.json || echo "No new fetched papers"
          git diff --cached --quiet || git commit -m "Add new extracted posts from arXiv"
          git push origin HEAD:${{ github.ref }}

  # summarize:
  #   runs-on: ubuntu-latest
  #   env:
  #     TZ: America/Los_Angeles
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: "3.11"

  #     - name: Install Python dependencies
  #       run: pip install -r requirements.txt

  #     - name: Summarize PDFs and generate posts
  #       run: |
  #         python scripts/summarize.py pdfs/ \
  #           --api_key "${{ secrets.OPENAI_TOKEN }}" \
  #           --verbose

  #     - name: Commit and push new posts
  #       run: |
  #         git config --global user.name "github-actions"
  #         git config --global user.email "github-actions@github.com"
  #         git add content/**/*.md || echo "No new posts"
  #         git diff --cached --quiet || git commit -m "Add new summarized posts from PDFs"
  #         git push origin HEAD:${{ github.ref }}

  build:
    runs-on: ubuntu-latest
    needs: fetch
    # needs: [fetch, summarize]
    env:
      HUGO_VERSION: 0.147.2
      HUGO_ENVIRONMENT: production
      TZ: America/Los_Angeles
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      - name: Cache Restore
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ runner.temp }}/hugo_cache
          key: hugo-${{ github.run_id }}
          restore-keys: hugo-

      - name: Configure Git
        run: git config core.quotepath false

      - name: Build with Hugo
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/" \
            --cacheDir "${{ runner.temp }}/hugo_cache"

      - name: Cache Save
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ runner.temp }}/hugo_cache
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4